### ISSUE TITLE
Correggere warning ed errore

### ISSUE THREAD

**Issue by iannellog** [LMarcoccia/Leolository#3]
Ho modificato il vostro codice (vedi allegato) per provarlo su due mesi completi (gennaio e marzo).
Il programma funziona quasi tutto ma emette due warning (uno per processo) e alla fine va in errore sull'operazione di fusione finale.
Ecco l'output sul mio computer:

> MacBook-Pro-di-Giulio:Leolository iannello$ python NYC.py
> inizio principale 1
> inizio principale 3
> NYC.py:69: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
>   andamento.to_csv(path)
> fine principale 3
> NYC.py:69: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
>   andamento.to_csv(path)
> fine principale 1
> NYC.py:189: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
> of pandas will change to not sort by default.
> 
> To accept the future behavior, pass 'sort=False'.
> 
> To retain the current behavior and silence the warning, pass 'sort=True'.
> 
>   andamento = pd.concat(df_per_file, ignore_index=True)
> Traceback (most recent call last):
>   File "/Applications/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
>     return self._engine.get_loc(key)
>   File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'giorni'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "NYC.py", line 248, in <module>
>     riordina_e_grafica(args)
>   File "NYC.py", line 192, in riordina_e_grafica
>     andamento['giorni'] = pd.to_datetime(andamento['giorni'])
>   File "/Applications/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 2980, in __getitem__
>     indexer = self.columns.get_loc(key)
>   File "/Applications/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2899, in get_loc
>     return self._engine.get_loc(self._maybe_cast_indexer(key))
>   File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'giorni'

Considerate che nel codice è fissa la directory e i nomi dei file che ho usato come input per cui non potete far girare il codice cosi' come è, ma dovete adattarlo al vostro caso (se prima rispondere all'issue #2 la questione si risolve automaticamente).

**Comment by LMarcoccia** [comment]
L'errore dovrebbe essere stato corretto. Ci faccia sapere se persiste.
